// Datos generados desde EVIA_Matriz_Maestra_Electrificados_Chile_v1.xlsx.
// Mantener prioridad y observaciones completas para uso interno; la app filtra lo visible al usuario.
const evModelsChile = [
  {
    id: "audi-e-tron-gt",
    brand: "Audi",
    model: "e-tron GT",
    technology: "BEV",
    category: "Sedán / Coupé",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.audi.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "audi-e-tron-sportback",
    brand: "Audi",
    model: "e-tron Sportback",
    technology: "BEV",
    category: "SUV / Crossover",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.audi.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "audi-q4-sportback-e-tron",
    brand: "Audi",
    model: "Q4 Sportback e-tron",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.audi.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "audi-q6-e-tron",
    brand: "Audi",
    model: "Q6 e-tron",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.audi.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "audi-q8-e-tron",
    brand: "Audi",
    model: "Q8 e-tron",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.audi.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "baic-eu5",
    brand: "BAIC",
    model: "EU5",
    technology: "BEV",
    category: "Sedán",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "C",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.baic.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "bmw-i4",
    brand: "BMW",
    model: "i4",
    technology: "BEV",
    category: "Sedán / Coupé",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.bmw.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "bmw-i5",
    brand: "BMW",
    model: "i5",
    technology: "BEV",
    category: "Sedán / Alta gama",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.bmw.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "bmw-i7",
    brand: "BMW",
    model: "i7",
    technology: "BEV",
    category: "Sedán / Alta gama",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "C",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.bmw.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "bmw-ix",
    brand: "BMW",
    model: "iX",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.bmw.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "bmw-ix1",
    brand: "BMW",
    model: "iX1",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.bmw.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "bmw-ix3",
    brand: "BMW",
    model: "iX3",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.bmw.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "byd-dolphin-ev",
    brand: "BYD",
    model: "Dolphin EV",
    technology: "BEV",
    category: "Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "byd-dolphin-mini",
    brand: "BYD",
    model: "Dolphin Mini",
    technology: "BEV",
    category: "Citycar / Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 168,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 10 BEV 2025/2026",
    featured: true,
  },
  {
    id: "byd-han-ev",
    brand: "BYD",
    model: "Han EV",
    technology: "BEV",
    category: "Sedán / Alta gama",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "byd-seal",
    brand: "BYD",
    model: "Seal",
    technology: "BEV",
    category: "Sedán",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "byd-sealion-7",
    brand: "BYD",
    model: "Sealion 7",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Lanzamiento 2026 / disponible",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "byd-tang",
    brand: "BYD",
    model: "Tang",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "byd-yuan-plus-ev",
    brand: "BYD",
    model: "Yuan Plus EV",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 103,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "byd-yuan-pro",
    brand: "BYD",
    model: "Yuan Pro",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "byd-shark",
    brand: "BYD",
    model: "Shark",
    technology: "PHEV",
    category: "Pickup",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "No es 100% eléctrico; debe mostrarse como PHEV",
    featured: true,
  },
  {
    id: "byd-song-pro",
    brand: "BYD",
    model: "Song Pro",
    technology: "PHEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.byd.com/cl",
    verifiedAt: "2026-06-19",
    reviewRequired: true,
    observations: "Verificar denominación exacta DM-i",
    featured: false,
  },
  {
    id: "changan-hunter-reev",
    brand: "Changan",
    model: "Hunter REEV",
    technology: "REEV",
    category: "Pickup",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.changan.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Motor térmico actúa como generador",
    featured: true,
  },
  {
    id: "changan-lumin",
    brand: "Changan",
    model: "Lumin",
    technology: "BEV",
    category: "Citycar",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.changan.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Lanzado en Chile durante 2026",
    featured: true,
  },
  {
    id: "chevrolet-blazer-ev",
    brand: "Chevrolet",
    model: "Blazer EV",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.chevrolet.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "chevrolet-bolt",
    brand: "Chevrolet",
    model: "Bolt",
    technology: "BEV",
    category: "Hatchback / Crossover",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 90,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.chevrolet.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "chevrolet-captiva-ev",
    brand: "Chevrolet",
    model: "Captiva EV",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.chevrolet.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "chevrolet-equinox-ev",
    brand: "Chevrolet",
    model: "Equinox EV",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.chevrolet.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "chevrolet-spark-euv",
    brand: "Chevrolet",
    model: "Spark EUV",
    technology: "BEV",
    category: "Citycar / SUV urbano",
    commercialStatus: "Anunciado / ficha en catálogo",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.chevrolet.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: true,
    observations: "Confirmar stock y fecha de inicio de ventas",
    featured: false,
  },
  {
    id: "citroen-e-berlingo",
    brand: "Citroën",
    model: "ë-Berlingo",
    technology: "BEV",
    category: "Comercial / Familiar",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.citroen.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "cupra-tavascan",
    brand: "Cupra",
    model: "Tavascan",
    technology: "BEV",
    category: "SUV mediano / Coupé",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.cupraofficial.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "dfsk-cargo-van-c35-ev",
    brand: "DFSK",
    model: "Cargo Van C35 EV",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.dfsk.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "dfsk-seres-3",
    brand: "DFSK",
    model: "Seres 3",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.dfsk.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "dongfeng-mage-ev",
    brand: "Dongfeng",
    model: "MAGE EV",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://dongfengchile.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "dongfeng-s50-ev",
    brand: "Dongfeng",
    model: "S50 EV",
    technology: "BEV",
    category: "Sedán",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://dongfengchile.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "dongfeng-vigo",
    brand: "Dongfeng",
    model: "Vigo",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible / ventas registradas 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://dongfengchile.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Aparece en ranking BEV enero 2026",
    featured: true,
  },
  {
    id: "fiat-500e",
    brand: "FIAT",
    model: "500e",
    technology: "BEV",
    category: "Citycar / Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.fiat.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "fiat-600e",
    brand: "FIAT",
    model: "600e",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.fiat.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "ford-e-transit-chasis",
    brand: "Ford",
    model: "E-Transit Chasis",
    technology: "BEV",
    category: "Comercial / Chasis",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.ford.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "ford-e-transit-furgon",
    brand: "Ford",
    model: "E-Transit Furgón",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.ford.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "gac-aion-es",
    brand: "GAC",
    model: "AION ES",
    technology: "BEV",
    category: "Sedán",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.gacmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "gac-aion-y",
    brand: "GAC",
    model: "AION Y",
    technology: "BEV",
    category: "SUV compacto / MPV",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.gacmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "geely-ex2",
    brand: "Geely",
    model: "EX2",
    technology: "BEV",
    category: "Citycar / Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 131,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.geely.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "geely-ex5",
    brand: "Geely",
    model: "EX5",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.geely.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "gwm-ora-03",
    brand: "GWM",
    model: "ORA 03",
    technology: "BEV",
    category: "Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.gwm.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Catálogo también lo muestra como GWM 03",
    featured: false,
  },
  {
    id: "hyundai-inster",
    brand: "Hyundai",
    model: "Inster",
    technology: "BEV",
    category: "Citycar / SUV urbano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.hyundai.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "hyundai-ioniq-5",
    brand: "Hyundai",
    model: "Ioniq 5",
    technology: "BEV",
    category: "SUV mediano / Crossover",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.hyundai.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "hyundai-kona-ev",
    brand: "Hyundai",
    model: "Kona EV",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.hyundai.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "jac-e-js1",
    brand: "JAC",
    model: "E-JS1",
    technology: "BEV",
    category: "Citycar / Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.jacautos.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "jac-e-js4",
    brand: "JAC",
    model: "E-JS4",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.jacautos.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "jac-ignite-30x",
    brand: "JAC",
    model: "Ignite 30X",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 118,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.jacautos.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 10 BEV 2025",
    featured: true,
  },
  {
    id: "jac-refine-cargo-ev",
    brand: "JAC",
    model: "Refine Cargo EV",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.jacautos.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "jaecoo-6",
    brand: "Jaecoo",
    model: "6",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.jaecoo.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "jmc-touring-ev",
    brand: "JMC",
    model: "Touring EV",
    technology: "BEV",
    category: "Comercial / Minibús",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "C",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.jmc.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "jmc-vigus-ev",
    brand: "JMC",
    model: "Vigus EV",
    technology: "BEV",
    category: "Pickup",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.jmc.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "kgm-torres-evx",
    brand: "KGM",
    model: "Torres EVX",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.kgm.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "kia-ev5",
    brand: "Kia",
    model: "EV5",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.kia.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "kia-ev6",
    brand: "Kia",
    model: "EV6",
    technology: "BEV",
    category: "SUV mediano / Crossover",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.kia.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "kia-ev9",
    brand: "Kia",
    model: "EV9",
    technology: "BEV",
    category: "SUV grande / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.kia.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "leapmotor-b10",
    brand: "Leapmotor",
    model: "B10",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Inicio de ventas mayo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.leapmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Venta iniciada en Chile en mayo 2026",
    featured: true,
  },
  {
    id: "maxus-edeliver-3",
    brand: "Maxus",
    model: "eDeliver 3",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 284,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://maxus.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 5 BEV acumulado abril 2026",
    featured: true,
  },
  {
    id: "maxus-edeliver-9",
    brand: "Maxus",
    model: "eDeliver 9",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://maxus.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "maxus-euniq-5",
    brand: "Maxus",
    model: "Euniq 5",
    technology: "BEV",
    category: "MPV / Familiar",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "C",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://maxus.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "maxus-mifa-9",
    brand: "Maxus",
    model: "Mifa 9",
    technology: "BEV",
    category: "MPV / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://maxus.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "maxus-t90-ev",
    brand: "Maxus",
    model: "T90 EV",
    technology: "BEV",
    category: "Pickup",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://maxus.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "mercedes-benz-eqs",
    brand: "Mercedes-Benz",
    model: "EQS",
    technology: "BEV",
    category: "Sedán / Alta gama",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "C",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mercedes-benz.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "mercedes-benz-evito",
    brand: "Mercedes-Benz",
    model: "eVito",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Ventas registradas 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mercedes-benz.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 10 BEV enero 2026",
    featured: false,
  },
  {
    id: "mg-mg4",
    brand: "MG",
    model: "MG4",
    technology: "BEV",
    category: "Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mgmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "mg-mg4-xpower",
    brand: "MG",
    model: "MG4 XPower",
    technology: "BEV",
    category: "Hatchback deportivo",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mgmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "mg-marvel-r",
    brand: "MG",
    model: "Marvel R",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mgmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "mg-zs-ev",
    brand: "MG",
    model: "ZS EV",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en mercado chileno",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mgmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: true,
    observations: "Verificar ficha vigente 2026",
    featured: true,
  },
  {
    id: "mg-cyberster",
    brand: "MG",
    model: "Cyberster",
    technology: "BEV",
    category: "Coupé / Roadster",
    commercialStatus: "Disponible / lanzamiento",
    priority: "C",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mgmotor.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: true,
    observations: "Confirmar stock local",
    featured: false,
  },
  {
    id: "mini-cooper-electrico",
    brand: "MINI",
    model: "Cooper Eléctrico",
    technology: "BEV",
    category: "Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mini.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "mini-cooper-se",
    brand: "MINI",
    model: "Cooper SE",
    technology: "BEV",
    category: "Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.mini.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: true,
    observations: "Posible duplicación generacional con Cooper Eléctrico",
    featured: false,
  },
  {
    id: "nammi-001",
    brand: "Nammi",
    model: "001",
    technology: "BEV",
    category: "Citycar / Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://dongfengchile.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 10 BEV 2025/enero 2026",
    featured: true,
  },
  {
    id: "nammi-dongfeng-e70",
    brand: "Nammi",
    model: "Dongfeng E70",
    technology: "BEV",
    category: "Sedán",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://dongfengchile.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "omoda-e5",
    brand: "Omoda",
    model: "E5",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.omoda.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "peugeot-e-2008",
    brand: "Peugeot",
    model: "e-2008",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.peugeot.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "peugeot-e-208",
    brand: "Peugeot",
    model: "e-208",
    technology: "BEV",
    category: "Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.peugeot.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "peugeot-e-partner",
    brand: "Peugeot",
    model: "e-Partner",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.peugeot.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "porsche-taycan",
    brand: "Porsche",
    model: "Taycan",
    technology: "BEV",
    category: "Sedán / Coupé",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.porsche.com/latin-america-es/_chile_/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Agrupa varias versiones y carrocerías",
    featured: false,
  },
  {
    id: "renault-kwid-e-tech",
    brand: "Renault",
    model: "Kwid E-Tech",
    technology: "BEV",
    category: "Citycar / Hatchback",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 207,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.renault.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 5 BEV acumulado abril 2026",
    featured: true,
  },
  {
    id: "renault-kangoo-e-tech",
    brand: "Renault",
    model: "Kangoo E-Tech",
    technology: "BEV",
    category: "Comercial / Furgón",
    commercialStatus: "Presencia histórica / verificar stock",
    priority: "C",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.renault.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: true,
    observations: "Verificar disponibilidad comercial actual",
    featured: false,
  },
  {
    id: "riddara-rd6",
    brand: "Riddara",
    model: "RD6",
    technology: "BEV",
    category: "Pickup",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.riddara.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "skoda-elroq",
    brand: "Skoda",
    model: "Elroq",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.skoda.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "smart-1",
    brand: "smart",
    model: "#1",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.kaufmann.cl/automoviles/smart",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: true,
  },
  {
    id: "smart-3",
    brand: "smart",
    model: "#3",
    technology: "BEV",
    category: "SUV coupé compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.kaufmann.cl/automoviles/smart",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 10 BEV enero 2026",
    featured: true,
  },
  {
    id: "smart-5",
    brand: "smart",
    model: "#5",
    technology: "BEV",
    category: "SUV mediano / Premium",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.kaufmann.cl/automoviles/smart",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    technology: "BEV",
    category: "Sedán",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 383,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.tesla.com/es_cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 5 BEV acumulado abril 2026",
    featured: true,
  },
  {
    id: "tesla-model-y",
    brand: "Tesla",
    model: "Model Y",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 396,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.tesla.com/es_cl",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 1 BEV acumulado abril 2026",
    featured: true,
  },
  {
    id: "toyota-bz4x",
    brand: "Toyota",
    model: "bZ4X",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.toyota.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "volkswagen-id-4",
    brand: "Volkswagen",
    model: "ID.4",
    technology: "BEV",
    category: "SUV mediano",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.volkswagen.cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "volvo-ec40",
    brand: "Volvo",
    model: "EC40",
    technology: "BEV",
    category: "SUV coupé compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.volvocars.com/cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "volvo-ex30",
    brand: "Volvo",
    model: "EX30",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en catálogo 2026",
    priority: "A",
    includeInApp: true,
    anacSales2026: 246,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.volvocars.com/cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "Top 5 BEV acumulado abril 2026",
    featured: true,
  },
  {
    id: "volvo-ex40",
    brand: "Volvo",
    model: "EX40",
    technology: "BEV",
    category: "SUV compacto",
    commercialStatus: "Disponible en mercado chileno",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.volvocars.com/cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
  {
    id: "volvo-ex90",
    brand: "Volvo",
    model: "EX90",
    technology: "BEV",
    category: "SUV grande / Premium",
    commercialStatus: "Disponible en mercado chileno",
    priority: "B",
    includeInApp: true,
    anacSales2026: null,
    sourceUrl: "https://www.autocosmos.cl/catalogo/segmentos?c=4",
    officialUrl: "https://www.volvocars.com/cl/",
    verifiedAt: "2026-06-19",
    reviewRequired: false,
    observations: "",
    featured: false,
  },
];

// Campos reservados para comparador EVIA y Scanner EVIA Pro.
// batteryKwh, rangeKm, rangeStandard, acChargingKw, dcChargingKw, connector,
// referencePriceClp, scannerCompatibility, scannerDataAvailable,
// obdAdapterRecommended, lastTechnicalVerification.
